### ISSUE TITLE
Content - Rubric Checklist

### ISSUE THREAD

**Issue by dagerebe** [kaylinenright/project-night-night#137]
- [x] Real, honest content on every page
- [x] An appropriate amount of content on every page
- [x] Content has an appropriate hierarchy
- [x] Each page has a distinct goal or task for the user
- [x] Proper spelling and grammar used
- [x] Content is completely relevant to the user
- [x] Content leads the user
- [x] Extra attention paid to every word on the page
- [x] Includes external links to relevant information within main content areas
