### ISSUE TITLE
Media Queries - Rubric Checklist

### ISSUE THREAD

**Issue by dagerebe** [kaylinenright/project-night-night#138]
- [x] Mobile first setup
- [x] Media queries for screens between 240 px – 2500 px
- [x] Flexible layouts supporting all screen sizes
- [x] Em-based media queries
- [x] Lots of small incremental changes to optimize each content piece
- [x] Extra attention paid to each content piece to create the best layout possible
