### ISSUE TITLE
Semantics - Rubric Checklist

### ISSUE THREAD

**Issue by dagerebe** [kaylinenright/project-night-night#139]
- [x] All content has appropriate HTML tags to add the best meaning
- [x] No extraneous `<br>` tags
- [x] Correctly using `<strong>, <em>, <b>and <i>` tags for their meaning not look
- [x] No extra, unneeded tags
- [x] Extra attention paid to all content (numbers, time, data;everything), to find the best tag
