### ISSUE TITLE
Header/Footer/Navigation - Rubric Checklist

### ISSUE THREAD

**Issue by dagerebe** [kaylinenright/project-night-night#140]
- [x] Different optimizations for different screen sizes
- [x] The current page is highlighted
- [x] Each optimization makes the most sense and uses the space efficiently
- [x] Each item in the navigation is appropriately titled and considered
- [x] Header and footer are both templated using Jekyll
