### ISSUE TITLE
Images, Icons & Fonts - Rubric Checklist

### ISSUE THREAD

**Issue by dagerebe** [kaylinenright/project-night-night#141]
- [x] Includes a 16 px and 32 px favicon
- [x] Appropriate use of SVG graphics
- [x] Using compressive JPGs for photos
- [x] Images scale appropriately
- [x] Includes an iconic font for all social media icons, and custom made icons
