### ISSUE TITLE
Code - Rubric Checklist

### ISSUE THREAD

**Issue by dagerebe** [kaylinenright/project-night-night#142]
- [x] Perfect indentation for all code
- [x] Little duplication in SCSS properties
- [x] Use of `@mixins` and `@variables` where needed
- [x] Using only classes for style hooks
- [x] Media queries associated with content blocks
- [x] Commenting of SCSS sections for find-ability and organization
- [x] Partials are organized, and broken up into multiple files that make sense (ie. typography, grids, etc)
- [x] All the CSS is in a single file that is generated from your style.scss file (which should be `@import` -ing all your partials)
