### ISSUE TITLE
Design, aesthetics and creativity - Rubric Checklist

### ISSUE THREAD

**Issue by dagerebe** [kaylinenright/project-night-night#143]
- [x] Overall design is functional and solves design problems as they arise
- [x] Leads users eye around page
- [x] Looks professional and consistent, there is a clear hierarchy and system to the design
- [x] Grid system is used for consistency
- [x] Design is original, and aesthetically appealing
