### ISSUE TITLE
File & folder naming and SEO - Rubric Checklist

### ISSUE THREAD

**Issue by dagerebe** [kaylinenright/project-night-night#144]
- [x] All files perfectly named: all lowercase, no spaces, dashes for word separation
- [x] Logical files names that represent the file’s purpose
- [x] Unique titles, and description meta tags for every page;as well as all other appropriate seo meta tags
- [x] Includes robots.txt, humans.txt, and sitemap.xml files, with appropriate information for the site
