### ISSUE TITLE
Github commits, issues and fixes - Rubric Checklist

### ISSUE THREAD

**Issue by dagerebe** [kaylinenright/project-night-night#145]
- [x] Proper commit messages that follow best practices outlined in class
- [x] Proper branching for developing specific features that follow best practices outlined in class
- [x] Issue creation for bugs
- [x] Bug fixing and closing issues on GitHub
