### ISSUE TITLE
Validation - Rubric Checklist

### ISSUE THREAD

**Issue by dagerebe** [kaylinenright/project-night-night#146]
- [ ] Fully valid (except for things like vendor prefixes and unregistered things like `<main>`)
- [x] All images have appropriate alt attributes
- [x] SCSS and Jekyll files and folders are setup properly and output to the correct folders

**Comment by dagerebe** [comment]
These are the issues right now. If someone could fix them that would be great and then we can check again on Sunday just to make sure.

<img width="1149" alt="screen shot 2016-03-11 at 11 22 21 am" src="https://cloud.githubusercontent.com/assets/6340285/13708282/adc9b88a-e77b-11e5-95d2-c188fbceecc8.png">
<img width="1148" alt="screen shot 2016-03-11 at 11 22 32 am" src="https://cloud.githubusercontent.com/assets/6340285/13708284/add0f244-e77b-11e5-977f-ca4a9783133f.png">
<img width="1142" alt="screen shot 2016-03-11 at 11 23 02 am" src="https://cloud.githubusercontent.com/assets/6340285/13708283/adce4bf2-e77b-11e5-9b3e-20b8b316de0f.png">
